### PR TITLE
Create "zh cn. json" for Simplified Chinese

### PR DESCRIPTION
**Pull request by Cata-a1138**
Create "zh cn. json" for Simplified Chinese
Delete "zh. json" because simplified Chinese should be "zh-cn. json" instead of "zh. json"
screenshot↓
image
image
image
image

### CODE REVIEW

**Comment by tabarra** [comment]
I don't understand why rename the file.  
Our current idea is to give it the unspecific name, and only if a concurrent translation with the same name comes up that we add the second part of the locale.  
For instance, we have Portuguese, and the file is named `pt.json` and only if there was different enough messages that we branched out those two into portuguese from brazil (pt_BR) and portuguese from portugal (pt_PT).  
  
And we had done that in the past, but it was not really required because portugal people can understand brazilian portuguese perfectly, so we deleted them and just kept `pt.json`, which is brazilian portuguese.  
  
With that in mind, wouldn't be more prudent to keep the language file only as `zh.json`?

**Comment by Cata-a1138** [comment]
Absolutely. 
People in Chinese mainland and Taiwan can understand simplified Chinese. 
I renamed this file because you wrote in translation support: Name the file using the language code in [this page](https://www.science.co.il/language/Locale-codes.php)
Sorry, my English is not good.

**Comment by tabarra** [comment]
It's alright... to be honest i'm not super sure if this is the correct decision.

**Comment by Cata-a1138** [comment]
Thank you for your efforts, txadmin is excellent
If there are no other problems, please send the pull request. I want to see Chinese in the translation option as soon as possible

**Comment by tabarra** [comment]
All of the translation PRs are frozen while i finish coding the v5 update.  
In a few days i'll review all of them (running `npm run locale:diff`) and I'll merge them if there are no issues.

**Comment by Cata-a1138** [comment]
Ok, thank you again

**Comment by tabarra** [comment]
Thanks again for the PR.  
I just modified a few lines to prepare for the v5 update, if you don't mind, can you also translate those?  
https://github.com/tabarra/txAdmin/blob/develop/locale/zh.json  
  
edit: don't forget to target your PR to the `develop` branch :)

**Comment by Cata-a1138** [comment]
No problem. Just a moment

**Comment by Cata-a1138** [comment]
Sorry, can you provide some screenshots or other content to help me translate?

**Comment by tabarra** [comment]
Mind joining the discord and pinging me there?  
https://discord.gg/txAdmin

**Comment by Cata-a1138** [comment]
ok
This is my username：Cata_a#0095

**Pull request merged**
