### PR TITLE
Updated ET locale.

### PR DESCRIPTION
**Pull request by ViskCY**
I am an estonian and made the text make more sense.

### CODE REVIEW

**Comment by tabarra** [comment]
Thanks for the PR.  
On `nui_menu.misc.help_message` can you change `TxAdmin` to `txAdmin`?

**Comment by ghost** [comment]
Yes done. Sorry for taking this long.

**Comment by tabarra** [comment]
Why is it `txAdmini` instead of `txAdmin`?

**Comment by tabarra** [comment]
Thanks again for the PR.  
I just modified a few lines to prepare for the v5 update, if you don't mind, can you also translate those?  
https://github.com/tabarra/txAdmin/blob/develop/locale/et.json  
  
edit: don't forget to target your PR to the `develop` branch :)

**Pull request closed without merging**
