### PR TITLE
locale nui_warning changes and fixed some typos

### PR DESCRIPTION
**Pull request by Latesttt**

### CODE REVIEW

**Comment by tabarra** [comment]
How good is the source on those translations?  
Need to be native level

**Comment by Aidan221** [comment]
I am danish and I can confirm that the da.json changes are native level. I have a polish friend that I just asked and he said that the pl changes are also native level. (Idk about the other ones since Im not the one who made this pr, just wanted to help out since these are some good changes)

**Review by tabarra — CHANGES_REQUESTED** [review]
All reviewed, just need a confirmation on `ro.json` and an revert on the last line break of `sv.json`

**Comment by Latesttt** [comment]
I can confirm that it's native level, I'm from Romania, Also what's wrong with the sv.json?

**Review by tabarra — APPROVED** [review]

**Pull request merged**
