### PR TITLE
Add missing weapons from DLCs to txAdmin kill internal kill logs

### PR DESCRIPTION
**Pull request by Gravxd**
Adds the missing weapons replacing the current "unknown" that shows in the txAdmin kill logs as well as updates the table containing all the references from GetHashKey to backticks to improve performance.

### CODE REVIEW

**Comment by Mycroft-Studios** [comment]
txAdmin currently does not use Lua 5.4, so the backticks will not work.
please change them back to `GetHashKey`

**Comment by Gravxd** [comment]
Small oversight, will change back and re push. Thanks 👍

**Comment by Gravxd** [comment]
Fixed that, bad habit with using Lua 5.4 - all set

**Comment by tabarra** [comment]
Thanks for the PR

**Pull request merged**
