### PR TITLE
added server restart & stop events to be fired to fivem side

### PR DESCRIPTION
**Pull request by NoobKeksTV**

### CODE REVIEW

**Comment by Arm-0001** [comment]
Doesn't work: 
hamy-is-Knowing

**Comment by NoobKeksTV** [comment]
fixxed & tested now. working for me

**Comment by tabarra** [comment]
I didn't add these events on purpose.  
They are called 100ms before server restarts, which give the server virtually no time to do anything with those events.  
  
People will try to plug their `esx.save()` and them complain it does not work.

**Comment by NoobKeksTV** [comment]
normally, esx does auto saves on disconnecting the players. so it should be a problem normally??

but tstill server should be able to do it in time even with 200 players (at least mine does lmao) 

you could put a bigger wait before tho :)

**Pull request closed without merging**
