### PR TITLE
Add Restart warnings to settings and trigger events

### LINKED ISSUE #217: Fire events before restart
Every time, when restart chat warning would show, fire event.

We could then handle this event, show our own message or to other stuff (like save things before restart).

Example:
```
TriggerServerEvent("txAdmin:scheduledRestart", 10)
```

And in our resources:

```
AddEventHandler('txAdmin:scheduledRestart', function(secondsToRestart)
  print("There will be restart in " .. secondsToRestart .. " seconds.")
  
  if secondsToRestart == 10 then
    saveAllUsersToDatabase()
  end
end)
```

### PR DESCRIPTION
**Pull request by Trsak**
Adds option to select how many minutes before restart should be message printed:
Settings

Also triggers event on those times, that can be handled like this in other resources:
```
RegisterNetEvent("txAdmin:events:restart")
AddEventHandler(
    "txAdmin:events:restart",
    function(data)
        if type(source) == "string" or source == nil or source == 0 then
            local remaingTime = tonumber(data.minutesRemaining)
            print("SERVER WILL BE RESTARTED IN " .. remaingTime)
        end
    end
)
```

Resolves #217

### CODE REVIEW

**Comment by Trsak** [comment]
Also resolves #99

**Comment by Sojobo** [comment]
Having an event that fires with the restart timer would be greatly appreciated. +1

**Comment by Trsak** [comment]
Any chance this can be looked into?

**Comment by tabarra** [comment]
Will be in this update, don't worry.  
-- I need to finish the server deployer part first.

**Comment by tabarra** [comment]
> Will be in this update, don't worry.
> -- I need to finish the server deployer part first.

Why do I do this to myself? LMAO  
Update must be out in a few hours and I haven't even looked at this....

**Comment by thephilluk** [comment]
Hi,
is this available in the 3.1.0 release or is this still waiting to be published to beta?
thanks,
Philip

**Pull request merged**
