### PR TITLE
Updated Chinese(Simplified, Traditional) lang

### PR DESCRIPTION
**Pull request by CCasusensa**
chinese simplified and chinese traditional separate

### CODE REVIEW

**Comment by w33ts** [comment]
Free Hong Kong.

**Review by tabarra — CHANGES_REQUESTED** [review]
Unfortunately I cannot accept this PR since it will break the config of all existing servers using `zh` as their language.  
Furthermore, I don't feel like this is required, since there are only about 30 chinese servers on the list (compared to about 800 combined for Brazil and Portugal, one that by itself probably shouldn't have been separated into two distinct languages).  
  
Pardon my ignorance, but how close are the two languages?  
If possible, just PR changes to the existing `zh.json` file with the most popular choice (simplified?).

**Comment by CCasusensa** [comment]
sorry, I have merged and change to simplified now

**Comment by tabarra** [comment]
Thank you.

**Review by tabarra — APPROVED** [review]

**Pull request merged**
