### PR TITLE
Console Commands Cache & Controls

### PR DESCRIPTION
**Pull request by lukaskabc**
Alternative GUI soultion for Commands Cache and Suggestion to add Server Controls to Consol page

### CODE REVIEW

**Comment by lukaskabc** [comment]
image

**Comment by w33ts** [comment]
You're definitely going to have to redo that and do it correctly for it to be accepted lol.

**Review by tabarra — CHANGES_REQUESTED** [review]
The idea is good, but this thing is a bit too ugly.  
This page is supposed to be non-scrollable, at least on desktop.  
I did some messing around, and this was my idea:  
ssdesktop  
ssmobile
  
If you still interested, here are some requisites:
- page must not cause scroll on a 1080p monitor
- responsive, must break the two columns into two rows at the right size to prevent bad ui (too shrunk, or overlaying)
- max length for the history
- max length for the button, must truncate with `...`
- the buttons shouldn't cut at the middle like the one from my screenshot

My code:
```css
.command-history{
    line-height: 2rem;
}
.command-history > a{
    color: #768192!important;
    border-radius: .2rem;
    padding: .075rem .4rem;
    margin-top: 20px;
    border: 1px solid #768192;
    text-decoration-line: none;
}
.command-history > a:hover{
    color: rgb(183, 189, 199)!important;
    border: 1px solid rgb(183, 189, 199);
}
```

```html
<div class="card-footer bg-dark">
    <div class="row">
        <div class="col-xl-6 col-lg-12 text-centerx">
            <form class="form-inline container-fluid" id="frmConsole">
                <div class="mx-auto">
                    <div class="form-group">
                        <input type="text" class="form-control console-input form-control-sm" id="cmdInput"
                                placeholder="Press enter to send. Up/Down arrows to navigate commands."
                                autocomplete="off" autocorrect="off" autocapitalize="off" 
                                spellcheck="false"{{it.disableWrite}}>
                    </div>
                    <button type="button" id="clearConsole"
                            class="btn btn-outline-light btn-sm mb-2">Clear Console
                    </button>
                    <button type="button" id="toggleAutoScroll"
                            class="btn btn-outline-light btn-sm mb-2">Disable Scroll
                    </button>
                    <a href="/fxserver/downloadLog" target="_blank"
                        class="btn btn-outline-light btn-sm mb-2">Download Log</a>
                    <button onclick="controlAction('restart')" class="btn btn-outline-danger btn-sm mb-2"
                        type="button" id="ctrl-restart" >RESTART</button> &nbsp;
                </div>
            </form>
        </div>
        <div class="col-xl-6 col-lg-12">
            <span class="text-light font-weight-bold">History:</span> <br>
            <div class="command-history">
                <a href="#">restart monitor</a>
                <a href="#">start blablabla</a>
                <a href="#">ban license:65a97df7a...</a>
                <a href="#">ban license:65a97df7a...</a>
                <a href="#">ban license:65a97df7a...</a>
                <a href="#">ban license:65a97df7a...</a>
                <a href="#">ban license:65a97df7a...</a>
            </div>
            
        </div>
    </div>
    
</div>
```

**Comment by tabarra** [comment]
Closed by #214   
Thanks for the suggestion.

**Pull request closed without merging**
