### PR TITLE
Swear master

### PR DESCRIPTION
**Pull request by JustQuik**
The best version of txadmin beta you could ever ask for. The one that hates you. A lot.

### CODE REVIEW

**Comment by w33ts** [comment]
Literally what

**Comment by JustQuik** [comment]
don't hide it you know you want it

**Review by Rhydium — APPROVED** [review]
Seems like a good addition to txAdmin. Approved by me

**Comment by w33ts** [comment]
I want it done right lmao

**Comment by JustQuik** [comment]
well all I did was edit the stuff i just gotta add back the stuff that makes it work or whatever idk

**Comment by jooaooalmeida** [comment]
What dash actually wants is it to be more aggressive

**Comment by tabarra** [comment]
nice meme

**Pull request closed without merging**
