### PR TITLE
Update vietnamese translation.

### PR DESCRIPTION
**Pull request by nkyo**
create vi.json for vietnamese translation

### CODE REVIEW

**Comment by tabarra** [comment]
Thanks, I'll have a look in a couple of weeks when the next update is ready

**Comment by tabarra** [comment]
Hey @nkyo I just reviewed the translation and found some errors.  
Could you please edit the label to bel `Vietnamese` and check the following keys below?

```
Keys validation failed on:
- nui_menu.misc.no_perms
- nui_menu.page_main.announcement.label
- nui_menu.page_main.clear_area.label
- nui_menu.page_main.clear_area.dialog_desc
- nui_menu.page_main.player_ids.label
- nui_menu.player_modal.ban.submit
- nui_menu.misc.action_unauthorized
- nui_menu.misc.general_no_perms
- nui_menu.page_main.clear_area.dialog_description
```

**Comment by tabarra** [comment]
Thanks again for the PR.  
I just modified a few lines to prepare for the v5 update, if you don't mind, can you also translate those?  
https://github.com/tabarra/txAdmin/blob/develop/locale/en.json  
  
edit: don't forget to target your PR to the `develop` branch :)

**Comment by nkyo** [comment]
@tabarra I updated V5 translation.

**Comment by tabarra** [comment]
Thanks for the translation.  
I just modified `humanizer_language` from `vn` to `vi`.

**Pull request merged**
