### PR TITLE
zh_TW.json

### PR DESCRIPTION
**Pull request by RyanL-29**
Screenshot 2021-06-11 121424
image

txAdmin in-game menu not tested. Reason: Can't change menu language

### CODE REVIEW

**Comment by tabarra** [comment]
Hey thanks for the PR!  
1. Unfortunately the menu is still not translatable because even the translation keys for English are not final, we changing it every few days. ;
2. You need to remove the `.vs` folder;
3. sorry for my ignorance, but how different is Chinese from Chinese traditional? I would like to prevent micro-segregation of translations, if possible.  

As soon as the menu translation is ready, I'll commit the English translation to all locale files, and you can edit after that, okay?

**Comment by RyanL-29** [comment]
> Hey thanks for the PR!
> 
> 1. Unfortunately the menu is still not translatable because even the translation keys for English are not final, we changing it every few days. ;
> 2. You need to remove the `.vs` folder;
> 3. sorry for my ignorance, but how different is Chinese from Chinese traditional? I would like to prevent micro-segregation of translations, if possible.
> 
> As soon as the menu translation is ready, I'll commit the English translation to all locale files, and you can edit after that, okay?

1.Sorry for commit the .vs file. Visual Studio automatic generate for that. 

2. The orginal chinese locale is not 100% translate and some the China word usage are different from Hong Kong and Taiwan. Also few peoples in Hong Kong and Taiwan can't read simplified chinese. The original chinese locale also contain some problem that the sentence combine with those parameter will become weird. But I don't really know the simplified chinese so just make up a traditional chinese one to improve the sentences and complete the whole translation.

3. Ok no problem. Love your in-game menu work

**Comment by tabarra** [comment]
I will hold this PR a bit more, when the menu english translation is finally available, I'll mention you here so you know you can update your translations, okay?  
Thanks again for the PR!

**Comment by RyanL-29** [comment]
It's ok.

**Comment by tabarra** [comment]
Unfortunately we were not ready for enabling menu locales and this caused issues.  
I don't know when we will have it ready.  
  
I will close this PR, can you please create a new pr just changing the specific translation file with the keys that are already present in the other zh.json file?  
I removed all the nui menu stuff from it.

**Pull request closed without merging**
