### PR TITLE
Update README.md - code cleanup

### PR DESCRIPTION
**Pull request by cdouth99**

### CODE REVIEW

**Comment by cdouth99** [comment]
just some small edits for a cleaner readme

**Comment by TasoOneAsia** [comment]
Probably would be a good idea to include some references to the most requested docs page (ie menu, development).

**Comment by cdouth99** [comment]
> Probably would be a good idea to include some references to the most requested docs page (ie menu, development).

Yeah I was just editing the looks, rather than contents. If you want, I'll add another version with updated information.

**Comment by TasoOneAsia** [comment]
Might as well add those changes, if you could.

**Pull request closed without merging**
