### PR TITLE
Remove zap ads

### PR DESCRIPTION
**Pull request by Marvisak**
Zap stinky I removed it

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
As much as you might dislike the ads, they help support the continued development of this open source project.

**Comment by bulva2** [comment]
Let's all be honest Zap is the worst game server provider I have ever seen. Pretty shame that both txA and FiveM choose them as their partners. I understand that they are probably paying well but they are horrible at providing their service. 😂

**Comment by jooaooalmeida** [comment]
> Let's all be honest Zap is the worst game server provider I have ever seen. Pretty shame that both txA and FiveM choose them as their partners. I understand that they are probably paying well but they are horrible at providing their service. 😂

Who else would sponsor txAdmin? You? Zap is basically the only company allowed inside FiveM, not much we could do :P (we also didn’t “choose” them, they reached us) feel free to contribute to the project if you wish, it’s open source 😃

**Comment by tabarra** [comment]
I talked to ZAP extensively before making a deal with them, so I won't keep discussing the same items again.  
Furthermore, this is an idiotic PR and an unsubstantiated criticism.

**Pull request closed without merging**
