### PR TITLE
feature: Supporting custom time input for banning

### PR DESCRIPTION
**Pull request by lze3**
**Usage**
* For the player pop-out:

* Manually banning via identifier:

### CODE REVIEW

**Comment by lze3** [comment]
Oops, I guess IntelliJ likes applying lots of whitespace changes.

**Comment by lze3** [comment]
Turns out I missed a few things.

**Comment by lze3** [comment]
Okay, I think now this is ready. Please let me know if any regressions were introduced in this branch and I'll get them fixed.

**Comment by tabarra** [comment]
Merged manually.

**Pull request closed without merging**
