### PR TITLE
Resource list Enhancement

### PR DESCRIPTION
**Pull request by Maximus7474**
Small refactor for the resource list, altered it so that each category is collapsible making it easier to navigate them.

image

The categories hide correctly when using the Default Resources and Started resource sliders.

I decided to alter the css style for the card to remove the blue highlight on top as it didn't  look great.

### CODE REVIEW

**Comment by tabarra** [comment]
Thanks for the PR! Do you mind making some adjustments?  
1. Drop fontawesome, you can just use the classes `icon-arrow-down` (to show) and `icon-arrow-up` (to hide). With `font-size: 75%; font-weight: bold;` I think it will look good.
2. Move the chevrons to the right.
3. For some reason there is some border radius not being respected in the table head, idk where the issue is.
4. Add a show all / collapse all button to the top of the page, near the filter buttons.

**Comment by Maximus7474** [comment]
Hi Tabarra,

Will look into that ;)

**Comment by Maximus7474** [comment]
Sorry to bother, seems like either I've set something up incorrectly or something has changed which I didn't account for.
Any suggestions ?
image

**Comment by tabarra** [comment]
Try deleting all node_modules folder, then running a single `npm i` from the root directory.

**Comment by Maximus7474** [comment]
Yeah, I F ed up when creating my dev env

**Comment by Maximus7474** [comment]
Sorry again, globals are undefined when launching it, just sticks in the `awaitHttp` promise inside of core/extras/banner.js

**Comment by tabarra** [comment]
Can you join https://discord.gg/txAdmin and ping me in the offtopic channel so I can help you?

**Comment by Maximus7474** [comment]
Chevrons set to the right and using the suggested style changes
image

**Comment by Maximus7474** [comment]
Added the switch 
image
Thought this was the best approach

**Comment by tabarra** [comment]
I changed the UI and implementation a little bit.
image

**Pull request merged**
