### PR TITLE
feat(spectate): set focus instead of teleporting admin to player

### PR DESCRIPTION
**Pull request by pachxl**
if a cheater is being spectated they can easily see the admin below them
by doing this the admin remains in their current position but still render all the ground around the spectated player, but the spectated player will have no idea they are being spectated

this is my first pr to anything so sorry if ive done anything wrong

### CODE REVIEW

**Comment by AquarDev** [comment]
Doesn't this break with how OneSync works?

**Comment by pachxl** [comment]
> Doesn't this break with how OneSync works?

break in what way? @AquarDev

**Comment by tabarra** [comment]
i think you wouldn't be able to hear people talking this way

**Comment by pachxl** [comment]
> i think you wouldn't be able to hear people talking this way

will give this a test and let you know

**Pull request closed without merging**
