### PR TITLE
Context Variable - Master Principal Identifier

### PR DESCRIPTION
**Pull request by ItsANoBrainer**
Add a new context variable users are able to utilize to automatically assign the master to any custom principal instead of just the default group.admin.

### CODE REVIEW

**Comment by tabarra** [comment]
Where the docs at?  
What if admin has no ids?  
What if has multiple?

**Comment by tabarra** [comment]
hello

**Comment by ItsANoBrainer** [comment]
I've been away from development for a few weeks and getting back today, I'll update this.

**Comment by tabarra** [comment]
Do you still need this?

**Comment by ItsANoBrainer** [comment]
I am touching base with QBCore team to see if this is something they're still wanting. I will close this PR for now. Thanks

**Pull request closed without merging**
