### PR TITLE
refactor(menu/spectate): general cleanup + cycling feature

### PR DESCRIPTION
**Pull request by TasoOneAsia**
This cleanups up our spectate system a little bit to hopefully help with readability and logic flow. 

But, much of it still relies heavily on side effects that make me weep :(

This also adds the ability cycle between players as a feature, so users wouldn't have to click on each individual player in order to spectate them.

Still needs to be tested for bucket compatibility and a few things I may have missed while writing.

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
~~Missed this when writing, but it appears I may have mixed up the Jooat hashes that target dynamic key mappings. These just need to be switched around~~

**Comment by TasoOneAsia** [comment]
Ready for scale testing.

**Review by Ekinoxx0 — APPROVED** [review]

**Comment by TheFantomas** [comment]
Any news? Waiting for something special or? :D

**Comment by tabarra** [comment]
> Any news? Waiting for something special or? :D

First we need to wait for Cfx to ungag the monitor resource, otherwise we would have real hard time diagnosing any errors in this script.  
Also conflicts, there are many conflicts in this PR.

**Comment by tabarra** [comment]
Used these changes, and rewrote a bit, then merged in e195017928f20d17a7d02e3d62b63da5c459dead

**Pull request closed without merging**
