### PR TITLE
finished german translation

### PR DESCRIPTION
**Pull request by melonenmario**
Hi,
the german translation was a mix with english and german, i finished it :)

[Discord: melonenmario#9292]

### CODE REVIEW

**Comment by tabarra** [comment]
Thanks for the PR! But I believe you haven't tested it :P
image  
  
Do you mind following the the translation contributing guide?  
https://github.com/tabarra/txAdmin/blob/develop/docs/translation.md#contributing

**Comment by melonenmario** [comment]
Oh.... Ouch. I fix it in the next days and test ist before uploading :)

**Comment by tabarra** [comment]
Any updates?

**Comment by melonenmario** [comment]
I'm really busy at the moment, but this weekend I have time and do it. 😅

**Comment by TasoOneAsia** [comment]
Update on this PR?

**Comment by tabarra** [comment]
Probably better to use #515 since it's fully tested.

**Comment by melonenmario** [comment]
Sorry that it took so long, I was very busy.
The translation should work fine now :)
Screenshot 2021-12-12 120147
Screenshot 2021-12-12 120223


However, it is not possible to change the title of the history tab (related history):
Screenshot 2021-12-12 120939
Screenshot 2021-12-12 120926

Also, I have an idea: a way to lock the server for everyone (also whitelisted players) except admins, for maintenance for example. Should I post my idea again somewhere?

**Comment by tabarra** [comment]
Thank you for the PR.  
There was 3 german PRs so unfortunately i had to select one (#515).  
If you want, please check the link below and comment any changes you think may be necessary.  
https://github.com/tabarra/txAdmin/pull/515

**Pull request closed without merging**
