### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by userzfr**
A new update for fr next my last close for my error for merj in master

### CODE REVIEW

**Comment by wowjeeez** [comment]
There already is a french translation, this was already pointed out in your previous PR.

**Comment by userzfr** [comment]
yes sorry but it was a correction but is no verry imprtante

**Comment by wowjeeez** [comment]
I mean if you feel that it corrects some mistakes feel free to keep it open. @tabarra passing this over to u

**Comment by tabarra** [comment]
Hey @Matdbx10, if there are corrections needed, can you please go to the link below and click on the button to edit and make a new PR?  
It's important that locale changes are made over the existing translation to guarantee it's always updated.  
https://github.com/tabarra/txAdmin/blob/develop/locale/fr.json  
  
Thanks.

**Pull request closed without merging**
