### PR TITLE
Added Dark Theme

### PR DESCRIPTION
**Pull request by w33ts**
So, I created a dark theme using the CoreUI branch recommended in the docs.

Lemme know if there's anything I need to fix.

### CODE REVIEW

**Comment by NonStopGamer** [comment]
I luv

**Comment by BlueSkyHusky** [comment]
i need that gimme

**Comment by RelliuG** [comment]
very nice +1

**Comment by pedrofcj** [comment]
+999!

**Comment by tydoo** [comment]
Its work with the 2.0 ?

**Comment by tabarra** [comment]
@tydoo no.

**Comment by tabarra** [comment]
Sadly not compatible with txAdmin v2.  
Still in the TODO list tho :)

**Comment by skittles-fivem** [comment]
NOT YET IM WORKING ON IT

**Pull request closed without merging**
