### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by user123441221** [comment]
were the translations done using some kind of google translator or smth like that?

**Comment by ghost** [comment]
no my Russian is just rough.

**Comment by user123441221** [comment]
too rough
the translations bring more confusion than clarity

**Comment by ghost** [comment]
you're more than welcome to commit changes. I have not natively spoken Russian is some time.

**Comment by tabarra** [comment]
@lurkmorr If you plan on contributing to the language file, this is a good time since in a few days i'm releasing another update.

**Pull request merged**
