### PR TITLE
Added an option to send scaleform message

### PR DESCRIPTION
**Pull request by DoluTattoo**
You can change the title of the scaleforms in _txAdminClient/txa_client.lua_ at line 2 (default "Staff announce")
You can change the time of the message in _txAdminClient/txa_server.lua_ at line 71 (default 3sec)

Hope you like it,
I love your job, awesome release

preview:
image

### CODE REVIEW

**Comment by tabarra** [comment]
That's useful.  
Will have to take a look after the next update.

**Comment by rex2630** [comment]
IT doesnt work

**Comment by DoluTattoo** [comment]
@rex2630

Its not up to date, i have to edit this.

**Comment by rex2630** [comment]
Ok,please do that,because i really like it :)

**Comment by rex2630** [comment]
Will u edit this anytime soon, please?

**Pull request closed without merging**
