### PR TITLE
Rewrote cl_logger.js in Lua

### PR DESCRIPTION
**Pull request by EvanDarwin**
- Removes the memory overhead of running a JS script in FiveM
- Fixed a bug where deaths by AI drivers would not be logged

### CODE REVIEW

**Review by tabarra — APPROVED** [review]

**Comment by LawyerMorty97** [comment]
Seems to log AI related deaths.

**Comment by tabarra** [comment]
Doesn't appear to be working correctly.  
I tested with death by NPC bullet and drowning, none of them even showed up in the log as a death. 
 
Needs a bit more testing.

**Review by tabarra — CHANGES_REQUESTED** [review]
check thee death reason detection cases

**Review by EvanDarwin — COMMENTED** [review]
I believe I found the bug, but I still need someone to test it with.

**Comment by FlawwsX** [comment]
That's not the bug.

**Comment by tabarra** [comment]
RIP PR?

**Comment by EvanDarwin** [comment]
Closed in favor of Flawws' #160

**Pull request closed without merging**
