### PR TITLE
feat(resource): Return Permissions with Auth

### PR DESCRIPTION
**Pull request by Justus-Braun**
Permissions will get returned with "txAdmin:events:adminAuth" event

### CODE REVIEW

**Comment by tabarra** [comment]
Can you describe in details what particular use case you have for this?  
Technically we are planning something different for informing other resources about the admin permissions.

**Comment by Justus-Braun** [comment]
It would allow me to have all permissions and admins be tracked by txAdmin. But a proper Permission System with Groups would be better.

**Comment by tabarra** [comment]
Uhh I actually need an use case for this information.

**Comment by Justus-Braun** [comment]
Sorry, 
I am creating an staff menu for my server which allows staff members to check up with player stats, spawn item, spawn vehicles and more.

When i would get the permissions from the auth event, i would translate txadmin permission to permissions in the staff menu.

This solves the issue when changeing permissions to not do that in 2 places.

But if there is a permission system rework in plan i dont want to interfear with that.

**Comment by tabarra** [comment]
I decided against merging this PR, because if I do so it will create an expectation of stability of the permission names (strings), and I do plan on changing them when rewriting the admin vault and management system.  
Thanks for the PR and suggestion anyways!

**Pull request closed without merging**
