### PR TITLE
Update hr.json

### PR DESCRIPTION
**Pull request by Ivek21**
Fixed some unfinished strings and spelling mistakes

### CODE REVIEW

**Comment by tabarra** [comment]
Thanks for the PR, but do you mind updating it to the current version of the translation file?  
Some keys have been added  
Updated one: https://github.com/tabarra/txAdmin/blob/develop/locale/hr.json  
  
image

**Comment by Ivek21** [comment]
Should be good now

**Comment by tabarra** [comment]
Still one more issue:  
```
Checking validity of the locale files based on 'en.json'.
[hr.json] Errors found in Croatian locale:
- nui_warning.instruction: must contain the placeholders ["%{key}","%{smart_count}","||||","%{key}","%{smart_count}"]

Errors found: 1
```

**Comment by Ivek21** [comment]
Should be good now, idk how that instruction appeared

**Comment by tabarra** [comment]
Thanks dude, will merge soon.

**Pull request merged**
